In [0]:
print("CASH FLOW")

CASH FLOW


In [0]:
pip install quandl

  Created wheel for inflection: filename=inflection-0.3.1-cp36-none-any.whl size=6077 sha256=d9c033455a6f156b1a1486630003daa4ac614aa25a094944f97e6885010b1e07
  Stored in directory: /root/.cache/pip/wheels/9f/5a/d3/6fc3bf6516d2a3eb7e18f9f28b472110b59325f3f258fe9211
Successfully built inflection


In [0]:
#dependencies
import quandl
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.svm import SVR
from sklearn.model_selection import train_test_split

In [0]:
from google.colab import files
uploaded = files.upload()

Saving train.csv to train.csv


In [0]:
import io
import pandas as pd
df2 = pd.read_csv(io.BytesIO(uploaded['train.csv']))
# Dataset is now stored in a Pandas Dataframe

In [0]:
df2 = df2[['CLIENT_OUT']]
print(df2.head(5))
#print(dfcash.head())

   CLIENT_OUT
0       91600
1      136500
2      335400
3      379000
4      344100


In [0]:
#Varialbe to predict 'n' days out
forecast_out = 30
#created new column ( a dependent var) - shifted n uniteds up
df2['Prediction'] = df2[['CLIENT_OUT']].shift(-forecast_out)
print(df2.tail(5))

        CLIENT_OUT  Prediction
287395       47500         NaN
287396       18100         NaN
287397        5000         NaN
287398       32300         NaN
287399       78100         NaN


In [0]:
#create independent data set
#convert df to numpy array
X = np.array(df2.drop(['Prediction'],1))
#remove last n rows
X = X[:-forecast_out]
print(X)

[[ 91600]
 [136500]
 [335400]
 ...
 [ 33800]
 [   400]
 [  7700]]


In [0]:
### Create the dependent data set (y)  #####
# Convert the dataframe to a numpy array (All of the values including the NaN's)
y = np.array(df2['Prediction'])
# Get all of the y values except the last 'n' rows
y = y[:-forecast_out]
print(y)

[193800.  70300. 384700. ...   5000.  32300.  78100.]


In [0]:
# Split the data into 80% training and 20% testing
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [0]:
# Create and train the Support Vector Machine (Regressor)
svr_rbf = SVR(kernel='rbf', C=1, gamma=0.1)
#svr_rbf.fit(x_train, y_train)

SVR(C=1, cache_size=200, coef0=0.0, degree=3, epsilon=0.1, gamma=0.1,
    kernel='rbf', max_iter=-1, shrinking=True, tol=0.001, verbose=False)

In [0]:
print(df2.head(8))

   CLIENT_OUT  Prediction
0       91600    193800.0
1      136500     70300.0
2      335400    384700.0
3      379000    481500.0
4      344100    563400.0
5      575300    929700.0
6      158200    665400.0
7      296500    498200.0


In [0]:
# Create and train the Linear Regression  Model
lr = LinearRegression()
# Train the model
lr.fit(x_train, y_train)

NameError: ignored

# New Section

In [0]:
# Testing Model: Score returns the coefficient of determination R^2 of the prediction. 
# The best possible score is 1.0
lr_confidence = lr.score(x_test, y_test)
print("lr confidence: ", lr_confidence)

lr confidence:  0.26563656770737787


In [0]:
# Set x_forecast equal to the last 30 rows of the original data set from Adj. Close column
x_forecast = np.array(df2.drop(['Prediction'],1))[-forecast_out:]
print(x_forecast)

[[ 66200]
 [ 21100]
 [ 34200]
 [ 34400]
 [ 22600]
 [  4200]
 [   500]
 [ 30400]
 [ 98100]
 [ 66700]
 [ 33900]
 [ 32800]
 [  4300]
 [  4000]
 [106300]
 [ 36100]
 [ 54800]
 [ 40500]
 [ 39200]
 [  8700]
 [  2300]
 [ 30700]
 [ 31600]
 [ 18500]
 [ 87300]
 [ 47500]
 [ 18100]
 [  5000]
 [ 32300]
 [ 78100]]


In [0]:
# Print linear regression model predictions for the next 'n' days
lr_prediction = lr.predict(x_forecast)
print(lr_prediction)

# Print support vector regressor model predictions for the next 'n' days
svm_prediction = svr_rbf.predict(x_forecast)
print(svm_prediction)

[212301.8158243  189136.62035266 195865.31349409 195968.04163365
 189907.08139938 180456.09255951 178555.62197758 193913.47884237
 228686.95408473 212558.63617321 195711.22128474 195146.21651714
 180507.45662929 180353.36441995 232898.80780685 196841.23081994
 206446.31186916 199101.24989035 198433.51698318 182767.4756997
 179480.17523366 194067.57105172 194529.84767976 187801.15453833
 223139.63454829 202696.73477508 187595.6982592  180867.00511777
 194889.39616823 218414.14012835]


AttributeError: ignored